routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	if (Auth::user()->keterangan == 'admin') {
		return redirect('admin');
	}else{
		return redirect('home');
	}
	})->middleware(['auth','verified']);

// Untuk Middleware jangan di hilangin untuk Security Login
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware(['auth','verified']);
Route::get('/pembayaran', 'PembayaranController@getPembayaran')->name('pembayaran')->middleware(['auth','verified']);

//<<<<<<< HEAD
Route::get('/afterVerified', function () {
	return view('afterVerified');
})->middleware(['auth','verified']);

Route::get('/oauth', function () {
	return view('oauth.index');
});


Route::get('/download', function () {
	return view('download.FormDownload');
});
Route::get('/UserProfile', function () {
	return view('UserProfile');
});


Route::resource('PendaftaranProgram', 'ProgramController')->middleware(['auth','verified']);



Route::resource('user', 'UserController')->middleware(['auth','verified']);




Route::get('/tes', function () {

	print_r(session()->all());
});


// Halaman Admin
Route::get('/admin', 'AdminController@index')->name('admin')->middleware(['auth','verified'],'admin');

app/Data_peserta.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Data_peserta extends Model
{
  protected $table = 'data_peserta';
	protected $primaryKey = 'id_program';
	protected $fillable = ['id_program','id_siswa'];
	public $timestamps = true;
}

app/LogActivityModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LogActivityModel extends Model
{
    protected $table = 'users_log';
    
    protected $fillable = [
        'subject', 'url', 'method', 'ip', 'agent', 'id_user'
    ];
}

app/Program.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Program extends Model
{
  protected $table = 'program';
	protected $primaryKey = 'id_program';
	protected $fillable = ['kode_program','gambar','nama_program','syarat','tempat_kegiatan','harga','pemateri','batas_pendaftaran','tanggal_awal','tanggal_akhir'];
	public $timestamps = true;
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use App\Notifications\ResetPasswordNotification;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    // ...
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = 'login';
    
     protected $primaryKey = 'id_user';
    protected $fillable = [
        'name', 'email', 'password','roles',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));
    }
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\User;


class AdminController extends Controller
{
    public function index()
    {
            return view('admin.dashboard');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\User;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $kategori = Auth::user()->kategori;
        $email = Auth::user()->email;
                // if ($kategori == "") {
                   // return redirect('afterVerified')->with('email', $email);;
                // }else{
                   return view('home');
                // }
    }
}

app/Http/Controllers/PembayaranController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PembayaranController extends Controller
{
    public function getPembayaran()
    {
        return view('pembayaran.FormPembayaran');
    }
}

app/Http/Controllers/ProgramController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Program;
use App\User;
use App\Data_peserta;

class ProgramController extends Controller
{


    public function index()
  {
      $data = Program::all();
      return view('PendaftaranProgram.FormPendaftaranProgram',['Program'=> $data]);

  }

    public function show($id)
    {
      $program = Program::find($id);
      $action = "Detail";

      $data_peserta= Data_peserta::
      selectRaw('data_peserta.id_program , data_peserta.id_user, users.name, users.kategori, users.foto')
      ->Join('users', 'data_peserta.id_user','=','users.id')
      ->where('data_peserta.id_program','=',$id)
      ->orderBy('users.name', 'ASC')
      ->get();

      $pendaftar = Data_peserta::
			selectRaw('data_peserta.created_at,data_peserta.id_user, users.name,  users.kategori, users.foto')
      ->Join('users', 'data_peserta.id_user','=','users.id')
      ->where('data_peserta.id_program','=',$id)
			->orderBy('created_at', 'DESC')
			->get();


      $kategori = Auth::user()->kategori;

      return view('PendaftaranProgram.DetailPendaftaranProgram', compact('program','data_peserta','pendaftar','action','kategori'));
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        // return view('edit', compact('anggota'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    public function updateAfterVerified(Request $request, $id)
    {
        $rules = [
            'nis' => 'required|min:2|max:32',
            
        ];
        $message = [
            'nis.required' => 'Nama Klasifikasi Harus di isi.',
            'nis.min' => 'Nama Klasifikasi Minimal 2 Huruf.',
            'nis.max' => 'Nama Klasifikasi Tidak Boleh lebih dari 32 kata.',
        ];

        $Validator = Validator::make(Input::all(),$rules,$message);

        if ($Validator->fails()) {
            return response()->json(array('errors' => $Validator->getMessageBag()->toArray()));
        }else{
            $klasifikasi = klasifikasiModel::find($id);
            $klasifikasi->nm_klasifikasi = $request->namaKlasifikasi;
            $klasifikasi->save();

            return response()->json(array("success"=>true));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/PendaftaranProgram/FormPendaftaranProgram.blade.php
@extends('layouts.MasterDasboard')

@section('content')

<!-- Page header -->
	<div class="page-header page-header-default">
		<div class="page-header-content">
			<div class="page-title">
				<h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Pendaftaran </span>Program</h4>
				<a class="heading-elements-toggle"><i class="icon-more"></i></a></div>

				<div class="heading-elements">
					<div class="heading-btn-group">
						<a href="#" class="btn btn-link btn-float has-text"><i class="icon-bars-alt text-primary"></i><span>Statistics</span></a>
						<a href="#" class="btn btn-link btn-float has-text"><i class="icon-calculator text-primary"></i> <span>Invoices</span></a>
						<a href="#" class="btn btn-link btn-float has-text"><i class="icon-calendar5 text-primary"></i> <span>Schedule</span></a>
					</div>
				</div>
			</div>

			<div class="breadcrumb-line"><a class="breadcrumb-elements-toggle"><i class="icon-menu-open"></i></a>
				<ul class="breadcrumb">
					<li><a href="index.html"><i class="icon-home2 position-left"></i> Home</a></li>
					<li class="active">Pendaftaran Program</li>
				</ul>

				<ul class="breadcrumb-elements">
					<li><a href="#"><i class="icon-comment-discussion position-left"></i> Support</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<i class="icon-gear position-left"></i>
							Settings
							<span class="caret"></span>
						</a>

						<ul class="dropdown-menu dropdown-menu-right">
							<li><a href="#"><i class="icon-user-lock"></i> Account security</a></li>
							<li><a href="#"><i class="icon-statistics"></i> Analytics</a></li>
							<li><a href="#"><i class="icon-accessibility"></i> Accessibility</a></li>
							<li class="divider"></li>
							<li><a href="#"><i class="icon-gear"></i> All settings</a></li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
		<!-- /page header -->


		<!-- Content area -->
		<div class="content">

			<!-- Floating labels -->
			<div class="row">
				<div class="col-md-12">
					<!-- Text inputs -->
					<div class="panel panel-flat">
						<div class="panel-heading">
							<h5 class="panel-title">Pendaftaran Program<a class="heading-elements-toggle"><i class="icon-more"></i></a></h5>
							<div class="heading-elements">
								<ul class="icons-list">
									<li><a data-action="collapse"></a></li>
									<li><a data-action="reload"></a></li>
									<li><a data-action="close"></a></li>
								</ul>
							</div>
						</div>

						<div class="panel-body">
							<div class="row">
								<div class="col-md-12">
									<div class="input-group" id="adv-search">
										<input type="text" class="form-control" placeholder="Pencarian Program" />
										<div class="input-group-btn">
											<div class="btn-group" role="group">
												<div class="dropdown dropdown-lg">
													<button data-action="reload" type="button" class="btn btn-primary"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
												</div>
											</div>
										</div>
									</div>
								</div>
	
					</div>
				</div>
			</div>
		</div>
					<!-- Detached content -->
					<div class="container-detached">
						<div class="content-detached">

							<!-- List -->
							<div class="row" >
								@foreach($Program as $no=>$prog)
								<div class="col-lg-6">
									<div class="panel panel-flat blog-horizontal blog-horizontal-2">
										<div class="panel-body">
											<div class="thumb">
												<a href="{{route('PendaftaranProgram.show',$prog->id_program)}}" data-toggle="modal">
													<img src="/img/gambar_program/{{$prog->gambar}}" class="img-responsive img-rounded" alt="" >
													<span class="zoom-image"><i class="icon-eye"></i></span>
												</a>
											</div>

											<div class="blog-preview">
												<div class="content-group-sm media blog-title stack-media-on-mobile text-left">
													<div class="media-body">
														<h5 class="text-semibold no-margin"><a href="{{route('PendaftaranProgram.show',$prog->id_program)}}" class="text-default">{{$prog->nama_program}}</a></h5>

														<ul class="list-inline list-inline-separate  text-muted">
															<li>{!! date('d-F-Y',strtotime($prog->tanggal_awal)) !!} S.D {!! date('d-F-Y',strtotime($prog->tanggal_akhir)) !!}</li>
														</ul>
													</div>


												</div>

												<p>Tempat : <br>{!! substr($prog->tempat_kegiatan,0,40) !!} <a href="{{route('PendaftaranProgram.show',$prog->id_program)}}">[...]</a>
											</div>
										</div>

										<div class="panel-footer panel-footer-condensed"><a class="heading-elements-toggle"><i class="icon-more"></i></a>
											<div class="heading-elements">
												<ul class="list-inline list-inline-separate heading-text">
													<li><i class="icon-users position-left text-primary"></i> 382</li>
													<li class="text-danger"><i class="icon-calendar52 position-left text-danger"></i> {!! date('d/m/Y',strtotime($prog->batas_pendaftaran)) !!}  </li>
													<li><i class="icon-coins position-left text-warning"></i>Rp.{{$prog->harga}}/Peserta
													</li>
												</ul>
												<a   href="{{route('PendaftaranProgram.show',$prog->id_program)}}" type="button" class="btn btn-danger btn-rounded  pull-right"><i class="icon-help position-left"></i> Detail<i class="icon-arrow-right14 position-right"></i></a>
											</div>
										</div>
									</div>
								</div>
								@endforeach
							</div>
							<!-- /list -->


							<!-- Pagination -->
							<div class="text-center content-group-lg pt-20">
								<ul class="pagination">
									<li class="disabled"><a href="#"><i class="icon-arrow-small-left"></i></a></li>
									<li class="active"><a href="#">1</a></li>
									<li><a href="#">2</a></li>
									<li><a href="#">3</a></li>
									<li><a href="#">4</a></li>
									<li><a href="#">5</a></li>
									<li><a href="#"><i class="icon-arrow-small-right"></i></a></li>
								</ul>
							</div>
							<!-- /pagination -->

						</div>
					</div>
				</div>

					@endsection

resources/views/afterVerified.blade.php
@extends('layouts.verifikasi')
@section('content')
<a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
            <div class="contact-image">
                <img src="/theme/assets/images/LogoEdupiad.jpg" alt="rocket_contact"/>
            </div>
            <form method="put" action="user/{{Session::get('email')}}">
                <h3>Mohon Isi Data Diri Anda</h3>
               <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text" name="Nis" class="form-control" placeholder="Masukan Nis *" value=""  required/>
                        </div>
                        <div class="form-group">
                            <input type="text" name="No_HP" class="form-control" placeholder="Masukan Nomer HP *" value="" required />
                        </div>
                        <div class="form-group">
                            <input type="date" name="Tanggal_lahir" class="form-control" placeholder="Masukan Tanggal Lahir *" value="" required />
                        </div>

                    </div>
                    <div class="col-md-6">
					<div class="form-group">
                            <input type="text" name="Tempat_lahir" class="form-control" placeholder="Masukan Tempat lahir *" value="" />
                    </div>
					<div class="form-group">
					<select class="form-control" required>
						<option class="form-control">Pilih Ketegori</option>
						<option class="form-control">Guru</option>
						<option class="form-control">Siswa</option>

					</select>
                    </div>
                        <div class="form-group">
                            <input type="submit" name="btnSubmit" class="btnContact" value="Verifikasi" />
                        </div>
                    </div>
                </div>
            </form>
</div>

				@endsection

resources/views/download/FormDownload.blade.php
@extends('layouts.MasterDasboard')

@section('content')

<!-- Page header -->
<form action="#" method="post">
	<div class="page-header page-header-default">
		<div class="page-header-content">
			<div class="page-title">
				<h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Download </span>Materi</h4>
				<a class="heading-elements-toggle"><i class="icon-more"></i></a></div>

				<div class="heading-elements">
					<div class="heading-btn-group">
						<a href="#" class="btn btn-link btn-float has-text"><i class="icon-bars-alt text-primary"></i><span>Statistics</span></a>
						<a href="#" class="btn btn-link btn-float has-text"><i class="icon-calculator text-primary"></i> <span>Invoices</span></a>
						<a href="#" class="btn btn-link btn-float has-text"><i class="icon-calendar5 text-primary"></i> <span>Schedule</span></a>
					</div>
				</div>
			</div>

			<div class="breadcrumb-line"><a class="breadcrumb-elements-toggle"><i class="icon-menu-open"></i></a>
				<ul class="breadcrumb">
					<li><a href="index.html"><i class="icon-home2 position-left"></i> Home</a></li>
					<li><a href="form_floating_labels.html">Forms</a></li>
					<li class="active">Download Materi</li>
				</ul>

				<ul class="breadcrumb-elements">
					<li><a href="#"><i class="icon-comment-discussion position-left"></i> Support</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<i class="icon-gear position-left"></i>
							Settings
							<span class="caret"></span>
						</a>

						<ul class="dropdown-menu dropdown-menu-right">
							<li><a href="#"><i class="icon-user-lock"></i> Account security</a></li>
							<li><a href="#"><i class="icon-statistics"></i> Analytics</a></li>
							<li><a href="#"><i class="icon-accessibility"></i> Accessibility</a></li>
							<li class="divider"></li>
							<li><a href="#"><i class="icon-gear"></i> All settings</a></li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
		<!-- /page header -->


		<!-- Content area -->
		<div class="content">

			<!-- Floating labels -->
			<div class="row">
				<div class="col-md-12">
					<!-- Text inputs -->
					<div class="panel panel-flat">
						<div class="panel-heading">
							<h5 class="panel-title">Download Materi<a class="heading-elements-toggle"><i class="icon-more"></i></a></h5>
							<div class="heading-elements">
								<ul class="icons-list">
									<li><a data-action="collapse"></a></li>
									<li><a data-action="reload"></a></li>
									<li><a data-action="close"></a></li>
								</ul>
							</div>
						</div>

						<div class="panel-body">
							<div class="row">
								<div class="col-md-12">
									<div class="input-group" id="adv-search">
										<div class="row">
											<div class="col-sm-1">  <button type="button" class="btn btn-primary btn-block">+</button>
											</div>
											<div class="col-sm-11"><input type="text" class="form-control" placeholder="Pencarian Program" />
											</div>

										</div>
										<div class="input-group-btn">
											<div class="btn-group" role="group">
												<div class="dropdown dropdown-lg">
													<button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
												</div>
											</div>
											
										</div>
										
									</div>
									<table class="table table-striped">
										<thead>
											<tr>
												<th>#</th>
												<th class="hidden-sm">Nama File</th>
												<th>Type</th>
												<th>Size</th>
												<th>Hits</th>
												<th>Action</th>
											</tr>
										</thead>
										<tbody>
											<tr>
												<td>1</td>
												<td class="text-nowrap">
													<h5><a href="javascript:;">TATA TERTIB &amp; TEMPAT TES PRA OSK 2019 SE JAWA TENGAH</a></h5>
												</td>
												<td><label class="label label-warning">.PDF</label></td>
												<td><label class="label label-warning">68.36KB</label></td>

												<td></td>
												<td class="text-nowrap">

													<a href="#" class="btn btn-primary"><i class="fa fa-download"></i> UNDUH</a>											
												</td>
											</tr>
											<tr>
												<td>2</td>
												<td class="text-nowrap">
													<h5><a href="javascript:;">TATA TERTIB &amp; TEMPAT TES PRA OSK 2019 SE JAWA TENGAH</a></h5>
												</td>
												<td><label class="label label-warning">.PDF</label></td>
												<td><label class="label label-warning">68.36KB</label></td>

												<td></td>
												<td class="text-nowrap">

													<a href="#" class="btn btn-primary"><i class="fa fa-download"></i> UNDUH</a>											
												</td>
											</tr>


										</tbody>
									</table>
								</div>

							</div>

							<!-- /floating labels -->

						</form>



					</div>
					<!-- /content area -->

				</div>


				@endsection

resources/views/layouts/LayoutLogin.blade.php
<!DOCTYPE html>
<html lang="zxx">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="assets/img/basic/favicon.ico" type="image/x-icon">
    <title>Edupiad - Member</title>
    <!-- CSS -->
    <link href="/theme/assets/css/icons/fontawesome/styles.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="/theme/assets/css/login/app.css">
    <style>
        .loader {
            position: fixed;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            background-color: #F5F8FA;
            z-index: 9998;
            text-align: center;
        }

        .plane-container {
            position: absolute;
            top: 50%;
            left: 50%;
        }

        .footer {
            color : white;
            
            
        }
    </style>
</head>
<body class="light">
    <!-- Pre loader -->
    <div id="loader" class="loader">
        <div class="plane-container">
            <div class="preloader-wrapper small active">
                <div class="spinner-layer spinner-blue">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div><div class="gap-patch">
                        <div class="circle"></div>
                    </div><div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>

                <div class="spinner-layer spinner-red">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div><div class="gap-patch">
                        <div class="circle"></div>
                    </div><div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>

                <div class="spinner-layer spinner-yellow">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div><div class="gap-patch">
                        <div class="circle"></div>
                    </div><div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>

                <div class="spinner-layer spinner-green">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div><div class="gap-patch">
                        <div class="circle"></div>
                    </div><div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="app">

 @yield('content')

        
    </div>

</div>


<div class="row">

</div>
</main>

</div>

</body>


<!-- #primary -->

<!-- Right Sidebar -->







</aside>
<!-- /.right-sidebar -->
<!-- Add the sidebar's background. This div must be placed
 immediately after the control sidebar -->
 <div class="control-sidebar-bg shadow white fixed"></div>
</div>
<!--/#app -->
<script src="/theme/assets/css/login/app.js"></script>
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Edupiad - Education Olimpiade Indonesia</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="/theme/assets/css/bootstrap.css" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Edupiad - Education Olimpiade Indonesia
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/verifikasi.blade.php
<html>
  <head>
  <title>Verifikasi</title>
    <link href="/theme/assets/css/gaya_verifikasi.css" rel="stylesheet" type="text/css">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </head>
  <body>
    <div class="container contact-form">
    @yield('content')
    </div>
  </body>
</html>